# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Build for Production

on: 
  push:
    branches:
      - staging
  pull_request:
    branches: 
      - staging

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: |
          rm -r .git
          ls -la
          cd build && git init
          pwd
          ls -la
          git add .
          git commit -m "(CI) added React build"
          git remote add origin https://github.com/dev-ureckon/ureckon-22-frontend.git
          git branch -M production
          git push -u origin production
          

